### ISSUE TITLE
Marquee animation doesn't play until browser window resize

### ISSUE THREAD

**Issue by telagraphic** [antonbobrov/node-marquee#1]
@antonbobrov Great plugin, I pulled down the repo and got it working for my project.

My client app is making a server request to get the data for the contents of the marquee.
It populates the marquee container but the animation doesn't start.
It does start when I change the viewport size, which is odd.

[My code is here](https://github.com/telagraphic/fakenews-webcams/blob/master/public/js/scipts.js) — short and simple.

I see there is a play & pause method, but not sure how to use?

Code works fine when when using server side rendering.

**Comment by antonbobrov** [comment]
Hello!
Thanks for the issue and for using the plugin.
I understood the problem. When you initialize the plugin, it has some text from the very beginning. Then after loading and parsing JSON data, you change the innerHTML of the marquee element. 
Unfortunately, the plugin did not support mutation changes.
Good news that it is now fixed. Run `npm i node-marquee@latest` and enjoy :)

**Comment by antonbobrov** [comment]
By the way, the "play" and "pause" methods are simple to use:
`const marquee = nodeMarquee({
    speed: 2,
    selector: '#node-marquee'
});
marquee.pause();
marquee.play();`
